apiVersion: v1
kind: Service
metadata:
  name: {{ include "mock-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "mock-chart.name" . }}
    version: active
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
